package com.malto4.pipdroid

/** Перк из лора Fallout NV; iconRes — сразу id ресурса, без круга через строку. */
data class Perk(val id: String, val name: String, val desc: String, val iconRes: Int)

val perks = listOf(
    Perk("1", "Action Boy", "With the Action Boy perk, you gain an additional 25 Action Points to use in V.A.T.S.", R.drawable.perk_action_boy),
    Perk("2", "Action Girl", "With the Action Girl perk, you gain an additional 25 Action Points to use in V.A.T.S.", R.drawable.perk_action_girl),
    Perk("3", "Adamantium Skeleton", "With the Adamantium Skeleton perk, your limbs only receive 50% of the damage they normally would.", R.drawable.perk_adamantium_skeleton),
    Perk("4", "Animal Friend", "At the first rank of this perk, animals simply won't attack. At the second rank, they will actually come to your aid in combat, but never against another animal.", R.drawable.perk_animal_friend),
    Perk("5", "Beautiful Beatdown", "Reduce the AP Cost of Unarmed Attacks in VATS", R.drawable.perk_challenge),
    Perk("6", "Better Criticals", "With the Better Criticals perk, you gain a 50% damage bonus every time a critical hit is scored on an opponent.", R.drawable.perk_better_criticals),
    Perk("7", "Better Healing", "While Arcade is a companion, the player regains more health from all sources.", R.drawable.perk_better_healing),
    Perk("8", "Black Widow", "In combat, you do 10% extra damage against male opponents. Outside of combat, you sometimes receive unique dialogue options when dealing with the opposite sex.", R.drawable.perk_black_widow),
    Perk("9", "Bloody Mess", "With the Bloody Mess perk, characters and creatures you kill will often explode into a red, gut-ridden, eyeball-strewn paste. Fun! Oh, and you'll do 5% more damage with all weapons.", R.drawable.perk_bloody_mess),
    Perk("10", "Built to Destroy", "The flamer that burns twice as bright burns half as long. All weapons have +3% chance to Critical Hit, but equipment condition decays 15% faster.", R.drawable.perk_built_to_destroy),
    Perk("11", "Cannibal", "With the Cannibal perk, when you're in Sneak mode, you gain the option to eat a corpse to regain Health. But every time you feed, you lose Karma, and if the act is witnessed, it is considered a crime against nature.", R.drawable.perk_cannibal),
    Perk("12", "Center of Mass", "You don't fool around with fancy trick shots. Straight to the midsection and down they go. In V.A.T.S., you do an additional 15% damage with attacks targeting the torso.", R.drawable.perk_center_of_mass),
    Perk("13", "Chemist", "With the Chemist perk, any chems you take last twice as long.", R.drawable.perk_chemist),
    Perk("14", "Chem Resistant", "Having the Chem Resistant perk means you're 50% less likely to develop an addiction to chems, like Psycho or Jet.", R.drawable.perk_chem_resistant),
    Perk("15", "Cherchez La Femme", "In combat, you do +10% damage against female opponents. Outside of combat, you'll sometimes have access to unique dialogue options when dealing with the same sex.", R.drawable.perk_cherchez_la_femme),
    Perk("16", "Child at Heart", "This perk greatly improves your interactions with children, usually in the form of unique dialogue options.", R.drawable.perk_child_at_heart),
    Perk("17", "Commando", "While using a rifle (or similar two-handed weapon), your accuracy in V.A.T.S. is significantly increased.", R.drawable.perk_commando),
    Perk("18", "Comprehension", "With the Comprehension perk, you gain one additional skill point whenever a skill book is read.", R.drawable.perk_comprehension),
    Perk("19", "Concentrated Fire", "With Concentrated Fire, your accuracy to hit any body part in V.A.T.S. increases slightly with each subsequent hit on that body part.", R.drawable.perk_concentrated_fire),
    Perk("20", "Confirmed Bachelor", "In combat, you do +10% damage against male opponents. Outside of combat, you'll sometimes have access to unique dialogue options when dealing with the same sex.", R.drawable.perk_confirmed_bachelor),
    Perk("21", "Contract Killer", "Once you have the Contract Killer perk, any good character you kill will have an ear on their corpse. This ear can then be sold to a certain person (whose identity is disclosed when you take the perk) for caps and negative Karma.", R.drawable.perk_contract_killer),
    Perk("22", "Cowboy", "You do 25% more damage when using any revolver, lever-action firearm, dynamite, knife, or hatchet.", R.drawable.perk_cowboy),
    Perk("23", "Cyborg", "You've made permanent enhancements to your body! The Cyborg perk instantly adds +10% to your Damage, Poison, and Radiation Resistances, and 10 points to the Energy Weapons skill.", R.drawable.perk_cyborg),
    Perk("24", "Demolition Expert", "With each rank of this perk, all of your explosive weapons do an additional 20% damage.", R.drawable.perk_demolition_expert),
    Perk("25", "Dream Crusher", "Something about your presence dampens others' desires to exceed. Any enemy's chance of getting critical hits on you is reduced by 50%.", R.drawable.perk_dream_crusher),
    Perk("26", "Educated", "With the Educated perk, you gain two more skill points every time you advance in level. This perk is best taken early on, to maximize its effectiveness.", R.drawable.perk_educated),
    Perk("27", "Empathy Synthesizer", "Your prefrontal cortex has been enhanced with the Empathy Synthesizer, increasing your Charisma by 1.", R.drawable.perk_empathy_synthesizer),
    Perk("28", "Enhanced Sensors", "While ED-E is a companion, the player can detect enemies at an increased range. Additionally, enemies will appear on the player's compass and can be targeted in V.A.T.S. even when cloaked.", R.drawable.perk_enhanced_sensors),
    Perk("29", "Entomologist", "With the Entomologist perk, you do an additional +50% damage every time you attack a mutated insect, like the radroach, giant ant, or radscorpion.", R.drawable.perk_entomologist),
    Perk("30", "Explorer", "When you choose the Explorer perk, every location in the world is revealed on your map. So get out there and explore!", R.drawable.perk_explorer),
    Perk("31", "Fast Metabolism", "With the Fast Metabolism perk, you gain a 20% Health bonus when using Stimpaks.", R.drawable.perk_fast_metabolism),
    Perk("32", "Fast Shot", "While using Guns and Energy Weapons, you fire 20% more quickly but your shots are 20% less accurate.", R.drawable.perk_fast_shot),
    Perk("33", "Ferocious Loyalty", "The power of your personality inspires die-hard loyalty from your followers. When you drop below 50% health, your companions temporarily gain much greater resistance to damage.", R.drawable.perk_ferocious_loyalty),
    Perk("34", "Finesse", "With the Finesse perk, you have a higher chance to score a critical hit on an opponent in combat, equivalent to 5 extra points of Luck.", R.drawable.perk_finesse),
    Perk("35", "Fortune Finder", "With the Fortune Finder perk, you'll find considerably more Nuka-Cola caps in containers than you normally would.", R.drawable.perk_fortune_finder),
    Perk("36", "Four Eyes", "While wearing any type of glasses, you have +1 PER. Without glasses, you have -1 PER.", R.drawable.perk_four_eyes),
    Perk("37", "Friend of the Night", "You are a true friend of the night. Your eyes adapt quickly to low-light conditions indoors and when darkness falls across the post-nuclear wasteland.", R.drawable.perk_friend_of_the_night),
    Perk("38", "Full Maintenance", "While Raul is a companion, the Condition of weapons and armor decays 75% slower.", R.drawable.perk_full_maintenance),
    Perk("39", "Ghastly Scavenger", "With Ghastly Scavenger, when you're in Sneak mode, you gain the option to eat a Super Mutant or Feral Ghoul corpse to regain Health. Every time you feed, you lose Karma, and if the act is witnessed, it is considered a crime against nature.", R.drawable.perk_ghastly_scavenger),
    Perk("40", "Good Natured", "You're Good Natured at heart, more prone to solving problems with your mind than violence. You gain +5 to Barter, Medicine, Repair, Science, and Speech, but have -5 to Energy Weapons, Explosives, Guns, Melee Weapons, and Unarmed.", R.drawable.perk_good_natured),
    Perk("41", "Grim Reaper's Sprint", "If you kill a target while in V.A.T.S., all of your Action Points are restored upon exiting V.A.T.S.", R.drawable.perk_grim_reaper),
    Perk("42", "Gunslinger", "While using a pistol (or similar one-handed weapon), your accuracy in V.A.T.S. is significantly increased.", R.drawable.perk_gunslinger),
    Perk("43", "Gun Nut", "You are obsessed with using and maintaining a wide variety of conventional firearms. With each rank of the Gun Nut perk, you gain an additional 5 points to the Small Guns and Repair skills.", R.drawable.perk_gun_nut),
    Perk("44", "Hand Loader", "You know your way around a reloading bench and don't let good brass and hulls go to waste. When you use Guns, you are more likely to recover cases and hulls. You also have all hand load recipes unlocked at any of the wasteland's reloading benches.", R.drawable.perk_hand_loader),
    Perk("45", "Heavy Handed", "Your melee and unarmed attacks do more damage, but less critical hit damage.", R.drawable.perk_heavy_handed),
    Perk("46", "Here and Now", "The Here and Now perk immediately grants an additional experience level, complete with all the advantages that brings.", R.drawable.perk_here_and_now),
    Perk("47", "Hit the Deck", "Your extensive familiarity with Explosives allows you to ignore a portion of their damage. Your Damage Threshold is increased by 25 against any and all Explosives -- even your own.", R.drawable.perk_hit_the_deck),
    Perk("48", "Hunter", "In combat, you do +75% Critical Damage against animals and mutated animals.", R.drawable.perk_hunter),
    Perk("49", "Hypertrophy Accelerator Strength Implant", "Your muscle mass has been enhanced with the Hypertrophy Accelerator, increasing your Strength by 1.", R.drawable.perk_hypertrophy_accelerator),
    Perk("50", "Impartial Mediation", "With the impartial mediation perk, you gain an extra 30 points to your Speech skill so long as you maintain a neutral Karma level.", R.drawable.perk_impartial_mediation),
    Perk("51", "Infiltrator", "The Infiltrator perk gives you a second attempt at a lock that you previously broke while trying to force it.", R.drawable.perk_infiltrator),
    Perk("52", "Intense Training", "With the Intense Training perk, you can put a single point into any of your S.P.E.C.I.A.L. attributes.", R.drawable.perk_intense_training),
    Perk("53", "Iron Fist", "With the Iron Fist perk, you do an additional 5 points of Unarmed damage per rank.", R.drawable.perk_iron_fist),
    Perk("54", "Jury Rigging", "You possess the amazing ability to repair any item using a roughly similar item. Fix a trail carbine with a hunting rifle, a Plasma Defender with a laser pistol, or even power armor with metal armor. How does it work? Nobody knows... except you.", R.drawable.perk_jury_rigging),
    Perk("55", "Kamikaze", "You have +10 Action Points but your reckless nature causes you to have -2 Damage Threshold.", R.drawable.perk_kamikaze),
    Perk("56", "Khan Trick", "By relying on the dirty unarmed fighting tricks of the Great Khans, you can throw dust into the eyes of your enemies, temporarily stunning them. Perform a Power Attack while moving left or right to execute the Khan Trick.", R.drawable.perk_khan_trick),
    Perk("58", "Lady Killer", "In combat, you do +10% damage against female opponents. Outside of combat, you'll sometimes have access to unique dialogue options when dealing with the opposite sex.", R.drawable.perk_lady_killer),
    Perk("59", "Laser Commander", "From the humble Laser Pistol to the mighty Gatling Laser, you do +15% damage and have +10% chance to critically hit with any laser weapon.", R.drawable.perk_laser_commander),
    Perk("60", "Lawbringer", "Once you have the Lawbringer perk, any evil character you kill will have a finger on their corpse. This finger can then be sold to a certain person (whose identity is disclosed when you take the perk) for caps and positive Karma.", R.drawable.perk_lawbringer),
    Perk("61", "Lead Belly", "With the Lead Belly perk, you take 50% less radiation every time you drink from an irradiated water source.", R.drawable.perk_lead_belly),
    Perk("62", "Legion Assault", "Caesar's elite cadre of bodyguards, the legendary praetorians, use an aggressive Legion Assault to brutalize enemies. Perform a Power Attack while running forward to execute the Legion Assault.", R.drawable.perk_legion_assault),
    Perk("63", "Life Giver", "With the Life Giver perk, you gain an additional 30 Hit Points.", R.drawable.perk_life_giver),
    Perk("64", "Light Step", "With the Light Step perk, you'll never set off an enemy's mines or floor-based traps.", R.drawable.perk_light_step_mines),
    Perk("66", "Daddy's Boy", "Just like dear old Dad, you’ve devoted your time to intellectual pursuits. You gain an additional 5 points to both the Science and Medicine skills.", R.drawable.perk_like_father_like_son),
    Perk("67", "Little Leaguer", "Years as the Vault little league MVP have honed your hitting and throwing. With every rank, you gain 5 points of Melee Weapons skill and 5 points of Explosives skill.", R.drawable.perk_little_leaguer),
    Perk("68", "Living Anatomy", "Living Anatomy allows you to see the health and Damage Threshold of any target. It also gives you a +5% bonus to damage against humans and non-feral ghouls.", R.drawable.perk_living_anatomy),
    Perk("69", "Logic Co-Processor Intelligence Implant", "Your cerebral cortex has been enhanced with the Logic Co-Processor, increasing your Intelligence by 1.", R.drawable.perk_logic_co_processor),
    Perk("70", "Long Haul", "You have learned how to pack mountains of gear for the long haul. Being over-encumbered no longer prevents you from using fast travel.", R.drawable.perk_long_haul),
    Perk("71", "Loose Cannon", "From frag grenades to throwing spears, you can throw weapons 30% faster at the cost of 25% less range", R.drawable.perk_loose_cannon),
    Perk("72", "Master Trader", "When you take the Master Trader perk, the price of every item you buy from a vendor is reduced by 25%.", R.drawable.perk_master_trader),
    Perk("73", "Math Wrath", "You are able to optimize your Pip-Boy's V.A.T.S. logic, reducing all AP costs by 10%.", R.drawable.perk_math_wrath),
    Perk("75", "Meltdown", "Foes killed by your Energy Weapons emit a corona of harmful energy.", R.drawable.perk_meltdown),
    Perk("76", "Miss Fortune", "Just when your enemies think they have the upper hand, Miss Fortune appears to turn their world upside down. Appearing only in V.A.T.S., she has the ability to snatch defeat from the jaws of victory.", R.drawable.perk_miss_fortune),
    Perk("77", "Mister Sandman", "With the Mister Sandman perk, when you're in Sneak mode, you gain the option to silently kill any human or Ghoul while they're sleeping. And, all Mister Sandman kills earn bonus XP.", R.drawable.perk_mister_sandman),
    Perk("78", "More Criticals", "You are more likely to cause Critical Hits in combat if you have this Perk. Each level of More Criticals will get you a +5% chance to cause a critical hit. This is a good thing.", R.drawable.perk_more_criticals),
    Perk("82", "Wired Reflexes", "Advanced technology from the Commonwealth has increased your reaction speed, giving you a higher chance to hit in V.A.T.S.", R.drawable.perk_ms08_wired_reflexes),
    Perk("83", "Hematophage", "This perk allows you to regain health by consuming Bloodpacks.", R.drawable.perk_ms09_hematophage),
    Perk("84", "Barkskin", "You've been exposed to Harold's mutation and your skin is now as hard as tree bark. As a result, you've gained a permanent +5% to Damage Resistance.", R.drawable.perk_ms10_barkskin),
    Perk("85", "Mysterious Stranger", "Gives you your own personal guardian angel... armed with a fully loaded .44 Magnum. With this perk, the Mysterious Stranger appears occasionally in V.A.T.S. mode to lend a hand, with deadly efficiency.", R.drawable.perk_mysterious_stranger),
    Perk("86", "NEMEAN Sub-Dermal Armor", "Your skin has been toughened by the NEMEAN Sub-Dermal Armor, increasing your total Damage Threshold by 4.", R.drawable.perk_nemean_sub_dermal_armor),
    Perk("87", "Nerd Rage!", "You've been pushed around long enough! With the Nerd Rage perk, your Strength is raised to 10 and you gain 15 points to Damage Threshold whenever your Health drops to 20% or below.", R.drawable.perk_nerd_rage),
    Perk("88", "Night Person", "When the sun is down, a Night Person gains +2 to both Intelligence and Perception (up to a maximum of 10). This perk directly affects your 'internal clock' and remains active both inside and outside.", R.drawable.perk_night_person),
    Perk("89", "Ninja", "The Ninja perk grants you the power of the fabled shadow warriors. When attacking, you gain a +15% critical chance on all Melee and Unarmed attacks. Additionally, Sneak attack criticals do 25% more damage than normal.", R.drawable.perk_ninja),
    Perk("90", "Nociception Regulator Endurance Implant", "Your nervous system has been enhanced with the Nociception Regulator, increasing your Endurance by 1.", R.drawable.perk_nociception_regulator),
    Perk("91", "Optics Enhancer Perception Implant", "Your optic nerve has been enhanced with the Optics Enhancer, increasing your Perception by 1.", R.drawable.perk_optics_enhancer),
    Perk("92", "Pack Rat", "You have learned the value of careful packing. Items with a weight of 2 or less weigh half as much for you.", R.drawable.perk_pack_rat),
    Perk("93", "Paralyzing Palm", "With Paralyzing Palm, you will sometimes perform a special V.A.T.S. palm strike that paralyzes your opponent for 30 seconds. Note that in order to perform the Paralyzing Palm, you must be completely unarmed.", R.drawable.perk_paralyzing_palm),
    Perk("94", "PHOENIX Monocyte Breeder", "Your regenerative ability has been enhanced by the PHOENIX Monocyte Breeder implant, causing you to slowly regenerate lost hit points.", R.drawable.perk_phoenix_monocyte_breeder),
    Perk("95", "Piercing Strike", "Piercing Strike makes all of your Unarmed and Melee Weapons (including thrown) negate 15 points of Damage Threshold on the target.", R.drawable.perk_piercing_strike),
    Perk("96", "Plasma Spaz", "You're just so excited about plasma that you can't (magnetically) contain yourself! The AP costs for all plasma weapons (including Plasma Grenades) are reduced by 20%.", R.drawable.perk_plasma_spaz),
    Perk("97", "Probability Calculator Luck Implant", "Your frontal lobe has been enhanced with the Probability Calculator, increasing your Luck by 1.", R.drawable.perk_probability_calculator),
    Perk("98", "Purifier", "As a purifier of the wasteland, you do +50% damage with Melee and Unarmed weapons against Centaurs, Nightstalkers, Spore Plants, Spore Carriers, Deathclaws, Super Mutants, and Feral Ghouls.", R.drawable.perk_purifier),
    Perk("99", "Pyromaniac", "With the Pyromaniac perk, you do +50% damage with fire-based weapons, like the Flamer and Shishkebab.", R.drawable.perk_pyromaniac),
    Perk("101", "Quick Draw", "Quick Draw makes all of your weapon equipping and holstering 50% faster.", R.drawable.perk_quick_draw),
    Perk("102", "Rad Child", "You truly are a rad child. As you go through the increasingly devastating stages of radiation sickness, you will regenerate more and more health.", R.drawable.perk_rad_child),
    Perk("103", "Rad Resistance", "Rad Resistance allows you to -- what else? -- resist radiation. This perk grants an additional 25% to Radiation Resistance.", R.drawable.perk_rad_resistance),
    Perk("104", "Ranger Takedown", "When caught without their weapons, NCR's rangers rely on the Ranger Takedown to quickly incapacitate opponents. Perform a Power Attack while moving backwards to execute a Ranger Takedown.", R.drawable.perk_ranger_takedown),
    Perk("105", "Rapid Reload", "Rapid Reload makes all of your weapon reloads 25% faster than normal.", R.drawable.perk_rapid_reload),
    Perk("106", "Reflex Booster Agility Implant", "Your central nervous node has been enhanced with the Reflex Booster, increasing your Agility by 1.", R.drawable.perk_reflex_booster),
    Perk("107", "Regular Maintenance", "While Raul is a companion, the Condition of weapons and armor decays more slowly.", R.drawable.perk_regular_maintenance),
    Perk("108", "Retention", "With the Retention perk, the bonuses granted by skill magazines last three times as long.", R.drawable.perk_retention),
    Perk("109", "Robotics Expert", "With the Robotics Expert perk, you do an additional 25% damage to any robot. Also, sneaking up on a hostile robot undetected and deactivating it will put that robot into a permanent shutdown state.", R.drawable.perk_robotics_expert),
    Perk("110", "Run 'n Gun", "The Run 'n Gun perk reduces accuracy penalties with one-handed Guns and Energy Weapons while walking or running.", R.drawable.perk_run_n_gun),
    Perk("111", "Scoundrel", "Take the Scoundrel perk, and you can use your wily charms to influence people -- each rank raises your Speech and Barter skills by 5 points.", R.drawable.perk_scoundrel),
    Perk("112", "Scribe Assistant", "While Veronica is a companion, the player can craft Workbench items through Veronica's dialogue.", R.drawable.perk_scribe_assistant),
    Perk("113", "Scribe Counter", "Scribes in the Brotherhood of Steel are often not well-trained in the combat use of the high-tech gear employed by Paladins. They rely on unarmed defensive moves like the Scribe Counter to keep enemies at bay. Perform a standard attack out of a block hit reaction to execute a Scribe Counter.", R.drawable.perk_scribe_counter),
    Perk("114", "Scrounger", "With the Scrounger perk, you'll find considerably more ammunition in containers than you normally would.", R.drawable.perk_scrounger),
    Perk("115", "Search and Mark", "While Rex is a companion, unequipped chems, firearms, and ammunition within a short distance are highlighted when you zoom the camera.", R.drawable.perk_search_and_mark),
    Perk("116", "Shotgun Surgeon", "With this perk, your precision with a scattergun is something to behold. When using shotguns, regardless of ammunition used, you ignore an additional 10 points of a target's Damage Threshold.", R.drawable.perk_shotgun_surgeon),
    Perk("117", "Silent Running", "With the Silent Running perk, running no longer factors into a successful sneak attempt.", R.drawable.perk_silent_running),
    Perk("118", "Size Matters", "You are obsessed with really big weapons. With each rank of this perk, you gain an additional 15 points to the Big Guns skill.", R.drawable.perk_size_matters),
    Perk("119", "Slayer", "The slayer walks the earth! The speed of all Melee Weapons and Unarmed attacks is increased by 30%.", R.drawable.perk_slayer),
    Perk("120", "Small Frame", "Due to your small size, you have +1 Agility but your limbs are more easily crippled (25% extra limb damage).", R.drawable.perk_small_frame),
    Perk("121", "Sniper", "With the Sniper perk, your chance to hit an opponent's head in V.A.T.S. is significantly increased.", R.drawable.perk_sniper),
    Perk("122", "Solar Powered", "With the Solar Powered perk, you gain an additional 2 points to Strength when in direct sunlight, and slowly regenerate lost Health.", R.drawable.perk_solar_powered),
    Perk("123", "Splash Damage", "When you're deep in enemy territory, you just start chucking grenades and hope for the best. All Explosives have a 25% larger area of effect when they detonate.", R.drawable.perk_splash_damage),
    Perk("124", "Spotter", "While Boone is a companion, hostile targets are highlighted whenever the player is actively aiming.", R.drawable.perk_spotting),
    Perk("125", "Spray and Pray", "Your attacks do much less damage to companions, allowing you to liberally spray an area with reckless abandon.", R.drawable.perk_spray_and_pray),
    Perk("126", "Stealth Girl", "While Lily is a companion, the duration of Stealth Boys is increased by 200% and all Sneak Attack Critical Hits do an additional 10% damage.", R.drawable.perk_stealth_girl),
    Perk("127", "Stonewall", "You gain +5 Damage Threshold against all Melee Weapons and Unarmed attacks and cannot be knocked down in combat.", R.drawable.perk_stonewall),
    Perk("128", "Strong Back", "With this perk, you can carry an additional 50 lbs. of equipment.", R.drawable.perk_strong_back),
    Perk("129", "Super Slam!", "All Melee Weapons (except thrown) and Unarmed attacks have a chance of knocking your target down.", R.drawable.perk_super_slam),
    Perk("130", "Survivalist", "You are a master of the outdoors. This Perk confers the ability to survive in hostile environments. You get a +20% bonus to Outdoorsman for survival purposes, for each level of this Perk.", R.drawable.perk_survivalist),
    Perk("131", "Survival Assistant", "+2% Poison and Radiation Resistance, +5 HP, +2 Medicine, +2 Science, +2% DR, +2 Sneak, +2 Speech, +1% Critical Chance", R.drawable.perk_survival_assistant),
    Perk("132", "Survival Expert", "+4% Poison and Radiation Resistance, +10 HP, +4 Medicine, +4 Science, +4% DR, +4 Sneak, +4 Speech, +2% Critical Chance", R.drawable.perk_survival_expert),
    Perk("133", "Survival Guru", "+6% Poison and Radiation Resistance, +15 HP, +6 Medicine, +6 Science, +6% DR, +6 Sneak, +6 Speech, +3% Critical Chance", R.drawable.perk_survival_guru),
    Perk("134", "Swift Learner", "With each level of Swift Learner your character will gain an additional +10% to experience whenever Experience Points are earned.", R.drawable.perk_swift_learner),
    Perk("135", "Tag!", "The Tag! perk allows you to select a fourth skill to be a Tag skill, which instantly raises it by fifteen points.", R.drawable.perk_tag),
    Perk("136", "Terrifying Presence", "In some conversations, you gain the ability to initiate combat while terrifying a mob of opponents, sending them fleeing away for safety.", R.drawable.perk_terrifying_presence),
    Perk("137", "The Professional", "Up close and personal, that's how you like it. Your Sneak Attack Criticals with pistols, revolvers, and submachine guns, whether Guns or Energy Weapons, all inflict an additional 20% damage.", R.drawable.perk_the_professional),
    Perk("138", "Thief", "With each rank of Thief perk, you gain an immediate bonus of 5 points to both the Sneak and Lockpick skills.", R.drawable.perk_thief),
    Perk("139", "Toughness", "With the Toughness perk, you gain +3 to overall Damage Threshold. This perk may be taken twice, with the second rank granting an additional +3.", R.drawable.perk_toughness),
    Perk("140", "Travel Light", "While wearing light armor or no armor, you run 10% faster.", R.drawable.perk_travel_light),
    Perk("141", "Trigger Discipline", "While using Guns and Energy Weapons, you fire 20% more slowly but are 20% more accurate.", R.drawable.perk_trigger_discipline),
    Perk("142", "Unstoppable Force", "Your martial might is truly legendary. You do a large amount of additional damage through enemy blocks with all Melee Weapons and Unarmed attacks.", R.drawable.perk_unstoppable_force),
    Perk("143", "Vigilant Recycler", "Waste not, want not. When you use Energy Weapons, you are more likely to recover drained ammunition. You also have more efficient recycling recipes available at the wasteland's workbenches.", R.drawable.perk_vigilant_recycler),
    Perk("144", "Weapon Handling", "Weapon Strength Requirements are now 2 points lower than normal for you.", R.drawable.perk_weapon_handling),
    Perk("145", "Whiskey Rose", "While Cass is a companion, she and the player gain Damage Threshold when they drink Whiskey. Additionally, the player does not suffer intelligence loss from consuming alcohol and ignores the negative effects of alcohol addiction.", R.drawable.perk_whiskey_rose),
    Perk("146", "Wild Wasteland", "Wild Wasteland unleashes the most bizarre and silly elements of post-apocalyptic America. Not for the faint of heart or the serious of temperament.", R.drawable.perk_wild_wasteland)
)


/** ITEMS/Clock/Мелодия звонка (roadmap, "Часы — UX-спецификация") — треки вселенной
 * Fallout, извлечённые из архивов игр (Git LFS, см. .gitattributes). */
data class RingtoneTrack(val displayName: String, val rawResId: Int)
val ringtoneTracks = listOf(
    RingtoneTrack("Bob Crosby — Happy Times", R.raw.ringtone_bob_crosby_happy_times),
    RingtoneTrack("The Ink Spots — I Don't Want to Set the World on Fire", R.raw.ringtone_ink_spots_idont),
    RingtoneTrack("The Ink Spots — Maybe", R.raw.ringtone_ink_spots_maybe),
    RingtoneTrack("Connie Allen — Rocket 69", R.raw.ringtone_connie_allen_rocket_69),
    RingtoneTrack("Elton Britt — Uranium Fever", R.raw.ringtone_elton_britt_uranium_fever),
    RingtoneTrack("Roy Brown — Good Rockin' Tonight", R.raw.ringtone_roy_brown_good_rockin_tonight),
    RingtoneTrack("The Five Stars — Atom Bomb Baby", R.raw.ringtone_five_stars_atom_bomb_baby),
    RingtoneTrack("Warren Smith — Uranium Rock", R.raw.ringtone_warren_smith_uranium_rock),
)